In [2]:
import numpy as np 
from scipy.sparse import csr_matrix

In [17]:
## เปลี่ยนแค่อันนี้ เลืิอก dimemsio 
dimension = 5 # change me ! 
p = .3
A = np.empty((dimension,dimension))
from random import uniform, randint
for i in range(dimension):
    for j in range(dimension):
        r = uniform(0,1)
        if r <= p:
            A[i][j] = randint(2, 100)
        else:
            A[i][j] = 0

A ## Sparse Matrix

array([[11., 25., 17., 51.,  0.],
       [20., 94.,  0., 38., 45.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  3.],
       [ 0.,  0.,  0., 94.,  0.]])

In [35]:
S = csr_matrix(A)
print(S)

  (0, 0)	11.0
  (0, 1)	25.0
  (0, 2)	17.0
  (0, 3)	51.0
  (1, 0)	20.0
  (1, 1)	94.0
  (1, 3)	38.0
  (1, 4)	45.0
  (3, 4)	3.0
  (4, 3)	94.0


#### Ordinal Encoder using Scipy

In [41]:
from sklearn.preprocessing import OrdinalEncoder
from numpy import asarray
data = np.array([['red'], ['green'], ['blue']])

data




array([['red'],
       ['green'],
       ['blue']], dtype='<U5')

In [42]:
encoder = OrdinalEncoder()
result = encoder.fit_transform(data)
result

array([[2.],
       [1.],
       [0.]])

#### One Hot encoder 

In [47]:
from sklearn.preprocessing import OneHotEncoder

result = OneHotEncoder(sparse=False).fit_transform(data)
data

array([['red'],
       ['green'],
       ['blue']], dtype='<U5')

In [48]:
print(result)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
